package company.zsh.first.dao.auto;

import company.zsh.first.model.auto.TPerson;
import company.zsh.first.model.auto.TPersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface TPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_person
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    long countByExample(TPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_person
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    int deleteByExample(TPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_person
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    @Delete({
        "delete from public.t_person",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_person
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    @Insert({
        "insert into public.t_person (name, age, ",
        "created_at)",
        "values (#{name,jdbcType=VARCHAR}, #{age,jdbcType=INTEGER}, ",
        "#{createdAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT CURRVAL('t_person_id_seq')", keyProperty="id", before=false, resultType=Integer.class)
    int insert(TPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_person
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    int insertSelective(TPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_person
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    List<TPerson> selectByExample(TPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_person
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    @Select({
        "select",
        "id, name, age, created_at",
        "from public.t_person",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("company.zsh.first.dao.auto.TPersonMapper.BaseResultMap")
    TPerson selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_person
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") TPerson record, @Param("example") TPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_person
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    int updateByExample(@Param("record") TPerson record, @Param("example") TPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_person
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    int updateByPrimaryKeySelective(TPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_person
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    @Update({
        "update public.t_person",
        "set name = #{name,jdbcType=VARCHAR},",
          "age = #{age,jdbcType=INTEGER},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TPerson record);
}