package company.zsh.first.model.auto;

import java.util.Date;

public class TPerson {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_person.id
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_person.name
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_person.age
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_person.created_at
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_person.id
     *
     * @return the value of public.t_person.id
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_person.id
     *
     * @param id the value for public.t_person.id
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_person.name
     *
     * @return the value of public.t_person.name
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_person.name
     *
     * @param name the value for public.t_person.name
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_person.age
     *
     * @return the value of public.t_person.age
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_person.age
     *
     * @param age the value for public.t_person.age
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_person.created_at
     *
     * @return the value of public.t_person.created_at
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_person.created_at
     *
     * @param createdAt the value for public.t_person.created_at
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_person
     *
     * @mbg.generated Wed Feb 03 20:11:14 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", age=").append(age);
        sb.append(", createdAt=").append(createdAt);
        sb.append("]");
        return sb.toString();
    }
}